name: Deploy Nuxt 3 to GitHub Pages

on:
  push:
    branches:
      - master # 或你的主要分支名稱，例如 master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # 或你使用的 Node.js 版本

      - name: Install dependencies
        run: npm install # 或 yarn install

      - name: Build Nuxt 3 app
        run: npm run generate # 或 yarn generate

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .output/public # 指向 Nuxt 3 的默認輸出目錄
